package mariadb;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Interface class About created by swing library.Shows the group members.
 */
public class aboutFrame extends javax.swing.JFrame {

    /**
     * Creates new form aboutFrame
     */
    public aboutFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        labelMarinho = new javax.swing.JLabel();
        labelIsa = new javax.swing.JLabel();
        labelVal = new javax.swing.JLabel();
        labelRhuan = new javax.swing.JLabel();
        labelYuri = new javax.swing.JLabel();
        imgMarinho = new javax.swing.JLabel();
        imgIsa = new javax.swing.JLabel();
        imgVal = new javax.swing.JLabel();
        imgRhuan = new javax.swing.JLabel();
        imgYuri = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        archive = new javax.swing.JMenu();
        authenticate = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        helpMenuBar = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(840, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Integrantes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 24))); // NOI18N
        jPanel1.setToolTipText("Integrantes");
        jPanel1.setMinimumSize(new java.awt.Dimension(840, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 955));

        labelMarinho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelMarinho.setText("Guilherme Marinho Bernardi");

        labelIsa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelIsa.setText("Isabella Carolina Silva de Araújo");

        labelVal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVal.setText("Valterci Almeida Secco Junior");

        labelRhuan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelRhuan.setText("Rhuan Alves Inocêncio");

        labelYuri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelYuri.setText("Yuri Marçal Ferreira");

        imgMarinho.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pc\\Downloads\\Eclipse\\MariaDB\\src\\mariadb\\guilherme.jpeg")); // NOI18N

        imgIsa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pc\\Downloads\\Eclipse\\MariaDB\\src\\mariadb\\isa.jpeg")); // NOI18N

        imgVal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pc\\Documents\\NetBeansProjects\\guiInterfaces\\src\\main\\java\\val.jpeg")); // NOI18N

        imgRhuan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pc\\Documents\\NetBeansProjects\\guiInterfaces\\src\\main\\java\\rhuan.jpeg")); // NOI18N

        imgYuri.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pc\\Documents\\NetBeansProjects\\guiInterfaces\\src\\main\\java\\yuri.jpeg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(imgMarinho)
                .addGap(6, 6, 6)
                .addComponent(imgIsa, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(imgVal))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(labelMarinho, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(labelIsa)
                .addGap(92, 92, 92)
                .addComponent(labelVal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(imgRhuan)
                .addGap(70, 70, 70)
                .addComponent(imgYuri))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(labelRhuan)
                .addGap(217, 217, 217)
                .addComponent(labelYuri))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgMarinho)
                    .addComponent(imgIsa)
                    .addComponent(imgVal))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(labelMarinho))
                    .addComponent(labelIsa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgRhuan)
                    .addComponent(imgYuri))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRhuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelYuri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        archive.setText("Archive");

        authenticate.setText("Authenticate");
        authenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticateActionPerformed(evt);
            }
        });
        archive.add(authenticate);

        jMenuItem1.setText("Main");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        archive.add(jMenuItem1);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        archive.add(exit);

        menuBar.add(archive);

        helpMenuBar.setText("Help");

        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        helpMenuBar.add(help);

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        helpMenuBar.add(about);

        menuBar.add(helpMenuBar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void authenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticateActionPerformed
        // TODO add your handling code here:
        loginGUI logFrame = new loginGUI();
        logFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_authenticateActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        mainMenu mainMenu = new mainMenu();
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
        helpFrame helpFrame = new helpFrame();
        helpFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_helpActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        aboutFrame aboutFrame = new aboutFrame();
        aboutFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenu archive;
    private javax.swing.JMenuItem authenticate;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem help;
    private javax.swing.JMenu helpMenuBar;
    private javax.swing.JLabel imgIsa;
    private javax.swing.JLabel imgMarinho;
    private javax.swing.JLabel imgRhuan;
    private javax.swing.JLabel imgVal;
    private javax.swing.JLabel imgYuri;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIsa;
    private javax.swing.JLabel labelMarinho;
    private javax.swing.JLabel labelRhuan;
    private javax.swing.JLabel labelVal;
    private javax.swing.JLabel labelYuri;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
